### ISSUE TITLE
Hello please give like to roblox  game for players to ttest

### ISSUE THREAD

**Issue by Cube5x59999** [chicken-boil/Not-very-easy-Obby#2]
# Please give the game link as there are soo many games is roblox

Roblox name
TheLongestDisplayNam (@ Computerph1)
(Roblox game developer)

**Comment by Cube5x59999** [comment]
Give link

**Comment by Cube5x59999** [comment]
H O W your game has sooooo many visits please tutorial by my game has not that much visits and what program you use for thumbnail?

**Comment by chicken-boil** [comment]
> Give link

https://www.roblox.com/games/5202348042/Not-very-easy-Obby

**Comment by chicken-boil** [comment]
> H O W your game has sooooo many visits please tutorial by my game has not that much visits and what program you use for thumbnail?

Try advertise the game to your friends, make something that makes players wanting to stay longer in the game to achieve, do some Roblox advertising.
I use Adobe Photoshop for thumbnail.

**Comment by Cube5x59999** [comment]
OK
thx

**Comment by Cube5x59999** [comment]
And how much players you get when it was first public?

**Comment by Cube5x59999** [comment]
What is Photoshop alternative because I use mobile to make pictures

**Comment by chicken-boil** [comment]
> And how much players you get when it was first public?

10-15 players

**Comment by chicken-boil** [comment]
> What is Photoshop alternative because I use mobile to make pictures

https://photopea.com/
