### ISSUE TITLE
why health.lua is set to blank? did you meant it to display the character health on the gui?

### ISSUE THREAD

**Issue by Cube5x59999** [chicken-boil/Not-very-easy-Obby#3]
Did you meant the script to display the player health?

The script is
```markdown
-- make a text label to display the health
-- position it and name it "playerHealthDisplay"
-- put this script inside the text label
-- make sure that this script is localScript
Local player = game.players.localPlayer
While wait() do
   Script.parent.text = player.Character.Humanoid.Health
End
```
I cannot test this script because my laptop is broken and if the script doesn't work so tell me

Roblox name (if you want to friend req me)
Computerph1

**Comment by Cube5x59999** [comment]
I'm trying to help ._.

**Comment by Cube5x59999** [comment]
And I am on tablet

**Comment by chicken-boil** [comment]
Not all scripts on here is updated to the ones that are currently in the game.
